train: /content/mean_teacher_student_yolov55/local_folder/train/images
val: /content/mean_teacher_student_yolov55/local_folder/val/images
zurich_path: /content/mean_teacher_student_yolov55/mini/train/images
nc: 2
names:
  0: person
  1: car
