train: /content/mean_teacher_student_yolov55/my_dataset/mid_clear/train/images
val: /content/mean_teacher_student_yolov55/my_dataset/mixed_val/images
val_clear: /content/mean_teacher_student_yolov55/my_dataset/mid_clear/val/images
val_fog: /content/mean_teacher_student_yolov55/my_dataset/mid_foggy_zurich/val/images
zurich_path: /content/mean_teacher_student_yolov55/my_dataset/mid_foggy_zurich/train/images
nc: 2
names:
  0: person
  1: car
